- generic [ref=e1]:
  - generic [ref=e2]:
    - banner [ref=e3]:
      - generic [ref=e4]:
        - link "Moneytoring" [ref=e5] [cursor=pointer]:
          - /url: /
          - img [ref=e6]
          - generic [ref=e9]: Moneytoring
        - generic [ref=e10]:
          - navigation [ref=e11]:
            - link "대시보드" [ref=e12] [cursor=pointer]:
              - /url: /dashboard
            - link "포트폴리오" [ref=e13] [cursor=pointer]:
              - /url: /portfolio
            - link "뉴스" [ref=e14] [cursor=pointer]:
              - /url: /news
          - button "다크 모드 토글" [ref=e106]:
            - img
    - main [ref=e15]:
      - generic [ref=e17]:
        - generic [ref=e18]:
          - heading "대시보드" [level=1] [ref=e19]
          - paragraph [ref=e20]: 실시간 주식 및 암호화폐 가격을 확인하세요.
        - generic [ref=e22]:
          - generic [ref=e23]:
            - img [ref=e24]
            - 'textbox "종목 검색 (예: Apple, AAPL)" [active] [ref=e27]': Apple
            - button [ref=e315]:
              - img [ref=e316]
          - list [ref=e321]:
            - listitem [ref=e322]:
              - button "AAPL Apple Inc Common Stock" [ref=e323]:
                - generic [ref=e324]:
                  - paragraph [ref=e325]: AAPL
                  - paragraph [ref=e326]: Apple Inc
                - generic [ref=e327]: Common Stock
            - listitem [ref=e328]:
              - button "APLE Apple Hospitality REIT Inc Common Stock" [ref=e329]:
                - generic [ref=e330]:
                  - paragraph [ref=e331]: APLE
                  - paragraph [ref=e332]: Apple Hospitality REIT Inc
                - generic [ref=e333]: Common Stock
            - listitem [ref=e334]:
              - button "603020.SS Apple Flavor & Fragrance Group Co Ltd Common Stock" [ref=e335]:
                - generic [ref=e336]:
                  - paragraph [ref=e337]: 603020.SS
                  - paragraph [ref=e338]: Apple Flavor & Fragrance Group Co Ltd
                - generic [ref=e339]: Common Stock
            - listitem [ref=e340]:
              - button "MLP Maui Land & Pineapple Company Inc Common Stock" [ref=e341]:
                - generic [ref=e342]:
                  - paragraph [ref=e343]: MLP
                  - paragraph [ref=e344]: Maui Land & Pineapple Company Inc
                - generic [ref=e345]: Common Stock
            - listitem [ref=e346]:
              - button "AAPI Apple iSports Group Inc Common Stock" [ref=e347]:
                - generic [ref=e348]:
                  - paragraph [ref=e349]: AAPI
                  - paragraph [ref=e350]: Apple iSports Group Inc
                - generic [ref=e351]: Common Stock
            - listitem [ref=e352]:
              - button "PAPL Pineapple Financial Inc Common Stock" [ref=e353]:
                - generic [ref=e354]:
                  - paragraph [ref=e355]: PAPL
                  - paragraph [ref=e356]: Pineapple Financial Inc
                - generic [ref=e357]: Common Stock
            - listitem [ref=e358]:
              - button "2788.T Apple International Co Ltd Common Stock" [ref=e359]:
                - generic [ref=e360]:
                  - paragraph [ref=e361]: 2788.T
                  - paragraph [ref=e362]: Apple International Co Ltd
                - generic [ref=e363]: Common Stock
            - listitem [ref=e364]:
              - button "164A.T Applepark Co Ltd Common Stock" [ref=e365]:
                - generic [ref=e366]:
                  - paragraph [ref=e367]: 164A.T
                  - paragraph [ref=e368]: Applepark Co Ltd
                - generic [ref=e369]: Common Stock
            - listitem [ref=e370]:
              - button "PINEAPP.KL Pineapple Resources Bhd Common Stock" [ref=e371]:
                - generic [ref=e372]:
                  - paragraph [ref=e373]: PINEAPP.KL
                  - paragraph [ref=e374]: Pineapple Resources Bhd
                - generic [ref=e375]: Common Stock
            - listitem [ref=e376]:
              - button "SUNE Pineapple Energy Inc Common Stock" [ref=e377]:
                - generic [ref=e378]:
                  - paragraph [ref=e379]: SUNE
                  - paragraph [ref=e380]: Pineapple Energy Inc
                - generic [ref=e381]: Common Stock
        - generic [ref=e28]:
          - heading "미국 증시" [level=2] [ref=e29]
          - generic [ref=e30]:
            - generic [ref=e107]:
              - paragraph [ref=e108]: S&P 500
              - paragraph [ref=e109]: $742.31
              - generic [ref=e110]:
                - img [ref=e111]
                - generic [ref=e114]: +0.56%
                - generic [ref=e115]: +$4.13
            - generic [ref=e116]:
              - paragraph [ref=e117]: NASDAQ 100
              - paragraph [ref=e118]: $714.71
              - generic [ref=e119]:
                - img [ref=e120]
                - generic [ref=e123]: +1.06%
                - generic [ref=e124]: +$7.47
            - generic [ref=e125]:
              - paragraph [ref=e126]: Dow Jones
              - paragraph [ref=e127]: $497.14
              - generic [ref=e128]:
                - img [ref=e129]
                - generic [ref=e132]: "-0.15%"
                - generic [ref=e133]: $-0.75
        - generic [ref=e43]:
          - heading "암호화폐 시장" [level=2] [ref=e44]
          - generic [ref=e45]:
            - generic [ref=e134]:
              - paragraph [ref=e135]: 전체 시가총액
              - paragraph [ref=e136]: $2.73T
              - generic [ref=e137]:
                - img [ref=e138]
                - generic [ref=e141]: "-2.29%"
                - generic [ref=e142]: 24h
            - generic [ref=e143]:
              - paragraph [ref=e144]: BTC 도미넌스
              - paragraph [ref=e145]: 0.00%
              - paragraph [ref=e146]: 비트코인 시장 점유율
            - generic [ref=e147]:
              - paragraph [ref=e148]: ETH 도미넌스
              - paragraph [ref=e149]: 9.94%
              - paragraph [ref=e150]: 이더리움 시장 점유율
            - generic [ref=e151]:
              - paragraph [ref=e152]: 공포/탐욕 지수
              - paragraph [ref=e153]: 34/100
              - paragraph
        - generic [ref=e62]:
          - heading "한국 증시" [level=2] [ref=e63]
          - generic [ref=e64]:
            - generic [ref=e154]:
              - paragraph [ref=e155]: 코스피
              - paragraph [ref=e156]: 7,981.41
              - generic [ref=e157]:
                - img [ref=e158]
                - generic [ref=e161]: +1.75%
                - generic [ref=e162]: "+137.40"
            - generic [ref=e163]:
              - paragraph [ref=e164]: 코스닥
              - paragraph [ref=e165]: 1,191.09
              - generic [ref=e166]:
                - img [ref=e167]
                - generic [ref=e170]: +1.20%
                - generic [ref=e171]: "+14.16"
            - generic [ref=e172]:
              - paragraph [ref=e173]: 코스피200
              - paragraph [ref=e174]: 1,243.17
              - generic [ref=e175]:
                - img [ref=e176]
                - generic [ref=e179]: +1.88%
                - generic [ref=e180]: "+23.00"
        - generic [ref=e77]:
          - generic [ref=e78]:
            - heading "미국 주식" [level=2] [ref=e79]
            - generic [ref=e80]:
              - paragraph [ref=e181]: "마지막 업데이트: 오후 3:53:10"
              - link "AAPL $298.87 +1.38%" [ref=e182] [cursor=pointer]:
                - /url: /stocks/AAPL
                - generic [ref=e183]:
                  - paragraph [ref=e185]: AAPL
                  - generic [ref=e186]:
                    - paragraph [ref=e187]: $298.87
                    - paragraph [ref=e188]: +1.38%
              - link "GOOGL $402.62 +3.94%" [ref=e189] [cursor=pointer]:
                - /url: /stocks/GOOGL
                - generic [ref=e190]:
                  - paragraph [ref=e192]: GOOGL
                  - generic [ref=e193]:
                    - paragraph [ref=e194]: $402.62
                    - paragraph [ref=e195]: +3.94%
              - link "MSFT $405.21 -0.63%" [ref=e196] [cursor=pointer]:
                - /url: /stocks/MSFT
                - generic [ref=e197]:
                  - paragraph [ref=e199]: MSFT
                  - generic [ref=e200]:
                    - paragraph [ref=e201]: $405.21
                    - paragraph [ref=e202]: "-0.63%"
              - link "AMZN $270.13 +1.62%" [ref=e203] [cursor=pointer]:
                - /url: /stocks/AMZN
                - generic [ref=e204]:
                  - paragraph [ref=e206]: AMZN
                  - generic [ref=e207]:
                    - paragraph [ref=e208]: $270.13
                    - paragraph [ref=e209]: +1.62%
              - link "TSLA $445.27 +2.73%" [ref=e210] [cursor=pointer]:
                - /url: /stocks/TSLA
                - generic [ref=e211]:
                  - paragraph [ref=e213]: TSLA
                  - generic [ref=e214]:
                    - paragraph [ref=e215]: $445.27
                    - paragraph [ref=e216]: +2.73%
          - generic [ref=e86]:
            - heading "암호화폐" [level=2] [ref=e87]
            - generic [ref=e88]:
              - paragraph [ref=e217]: "마지막 업데이트: 오후 3:53:10"
              - generic [ref=e218]:
                - paragraph [ref=e221]: BTC
                - generic [ref=e222]:
                  - paragraph [ref=e223]: $79,801.00
                  - paragraph [ref=e224]: "-1.45%"
              - generic [ref=e225]:
                - paragraph [ref=e228]: ETH
                - generic [ref=e229]:
                  - paragraph [ref=e230]: $2,268.07
                  - paragraph [ref=e231]: "-1.46%"
              - generic [ref=e232]:
                - paragraph [ref=e235]: XRP
                - generic [ref=e236]:
                  - paragraph [ref=e237]: $1.43
                  - paragraph [ref=e238]: "-1.41%"
              - generic [ref=e239]:
                - paragraph [ref=e242]: SOL
                - generic [ref=e243]:
                  - paragraph [ref=e244]: $91.27
                  - paragraph [ref=e245]: "-4.13%"
              - generic [ref=e246]:
                - paragraph [ref=e249]: ADA
                - generic [ref=e250]:
                  - paragraph [ref=e251]: $0.27
                  - paragraph [ref=e252]: "-2.79%"
        - generic [ref=e94]:
          - heading "한국 주식" [level=2] [ref=e95]
          - generic [ref=e253]:
            - generic [ref=e255]:
              - generic [ref=e256]:
                - paragraph [ref=e257]: 삼성전자
                - paragraph [ref=e258]: "005930"
              - generic [ref=e259]:
                - paragraph [ref=e260]: ₩296,000
                - generic [ref=e261]:
                  - img [ref=e262]
                  - generic [ref=e265]: +4.23%
            - generic [ref=e267]:
              - generic [ref=e268]:
                - paragraph [ref=e269]: SK하이닉스
                - paragraph [ref=e270]: "000660"
              - generic [ref=e271]:
                - paragraph [ref=e272]: ₩-1,970,000
                - generic [ref=e273]:
                  - img [ref=e274]
                  - generic [ref=e277]: "-0.30%"
            - generic [ref=e279]:
              - generic [ref=e280]:
                - paragraph [ref=e281]: 현대차
                - paragraph [ref=e282]: "005380"
              - generic [ref=e283]:
                - paragraph [ref=e284]: ₩712,000
                - generic [ref=e285]:
                  - img [ref=e286]
                  - generic [ref=e289]: +0.28%
            - generic [ref=e291]:
              - generic [ref=e292]:
                - paragraph [ref=e293]: LG화학
                - paragraph [ref=e294]: "051910"
              - generic [ref=e295]:
                - paragraph [ref=e296]: ₩392,500
                - generic [ref=e297]:
                  - img [ref=e298]
                  - generic [ref=e301]: +1.29%
            - generic [ref=e303]:
              - generic [ref=e304]:
                - paragraph [ref=e305]: 카카오
                - paragraph [ref=e306]: "035720"
              - generic [ref=e307]:
                - paragraph [ref=e308]: ₩45,950
                - generic [ref=e309]:
                  - img [ref=e310]
                  - generic [ref=e313]: +6.98%
  - button "Open Next.js Dev Tools" [ref=e102] [cursor=pointer]:
    - img [ref=e103]
  - alert [ref=e314]